### ISSUE TITLE
Which training sets were used for the precomputed boxes?

### ISSUE THREAD

**Issue by rbgirshick** [gidariss/AttractioNet#2]
Hi Spyros, can you add a note to the readme indicating which training sets were used for the pre-computed boxes on VOC and COCO? (E.g., for COCO did you use 2014 train only or 2014 train + val?) Thanks!

**Comment by gidariss** [comment]
Hi Ross, 
The box proposals of the VOC and the COCO datasets were generated by a model trained on the COCO 2014 train set. I also updated the readme with this info.

**Comment by rbgirshick** [comment]
Thanks for the clarification!
