### ISSUE TITLE
Cannot load pretrained model

### ISSUE THREAD

**Issue by erinchen824** [gidariss/AttractioNet#3]
It seems that models are stored in google drive and I can not fetch it. Is there any other way to download the files? Thx.

**Comment by gidariss** [comment]
@YanjunChen Hi there, can you download it from the following link: 
https://mega.nz/#!r90F3KJS!TM-slQgOF4OFWnVJrgZVr0S8aSn-f_s_IVFigbnMWrI

Spyros

**Comment by erinchen824** [comment]
@gidariss Thx a lot, it works!!!
