### ISSUE TITLE
an error when I ran the demo_AttractioNet.m

### ISSUE THREAD

**Issue by geekvc** [gidariss/AttractioNet#4]
### an error occurred like this:
![image](https://cloud.githubusercontent.com/assets/10766005/19888514/053aa92e-a06a-11e6-8162-cbc23939838d.png)
### and
![image](https://cloud.githubusercontent.com/assets/10766005/19888723/71ddf328-a06b-11e6-8b81-30736d0bcf94.png)
### and I Tracked the code, and found when the function was called, the error occurred:
![image](https://cloud.githubusercontent.com/assets/10766005/19888439/9adcc51c-a069-11e6-8dee-f1a86658e456.png)
### next step:
![image](https://cloud.githubusercontent.com/assets/10766005/19888468/c2547f9a-a069-11e6-8720-8ebbe9d648da.png)
I don't know how to fix it.
my matlab version are 2013b and 2014a, and I am not sure this error was caused by the matlab version.
I am downloading the 2014b.
The  environment: Tesla K40c + ubuntu 14.04
thank you in advance!!!

**Comment by gidariss** [comment]
Hi @geekvc. The error that you get is not related to matlab but that you ran out of GPU memory when you try to apply the network. How many Gbytes your GPU has? Have you built caffe with the cudnn library activated?

Spyros

**Comment by geekvc** [comment]
## Thank you for your reply.

## The first time I ran the model in Titanz, which has 6Gbytes GPU memory, matlab version 2013b, and built caffe with USE_CUDNN := 1 in Makefile.config, and the process of built caffe with no error.

## when I ran the demo_AttractioNet.m in matlab, an error occurred:

![image](https://cloud.githubusercontent.com/assets/10766005/20009803/cf8d10d6-a2e0-11e6-8f24-e87f5d17950e.png)

## Then I removed the USE_CUDNN := 1 in Makefile.config, and built caffe and matcaffe again, when I ran the demo_AttractioNet.m, this situation is much better than the previous. However, still out of memory:

![image](https://cloud.githubusercontent.com/assets/10766005/20010105/e4a32a72-a2e1-11e6-8964-bb8567b879bd.png)

## After that, I thought the main reason is the GPU memory, then I ran it in K40, which has 12Gbytes GPU memory, matlab version 2014a, and built caffe with USE_CUDNN := 1 in Makefile.config, and the process of built caffe with no error.

## Everything is ok, thank you very much!
